export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const LOAD_EMPLOYEE = 'LOAD_EMPLOYEE';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_PROJECTS = 'SET_USER_PROJECTS';
export const SET_USER_TASKS = 'SET_USER_TASKS';
export const CHANGE_USER_SKILL = 'CHANGE_USER_SKILL';
export const CHANGE_USER_SKILL_LEVEL = 'CHANGE_USER_SKILL_LEVEL';
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';

export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_PROJECTS = 'SET_PROJECTS';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const SET_PROJECT_EMPLOYEES = 'SET_PROJECT_EMPLOYEES';
export const SET_PROJECT_TASKS = 'SET_PROJECT_TASKS';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const DELETE_PROJECT_EMPLOYEE = 'DELETE_PROJECT_EMPLOYEE';
export const ADD_PROJECT_EMPLOYEE = 'ADD_PROJECT_EMPLOYEE';
export const SET_PROJECT_TASKS_STORE = 'SET_PROJECT_TASKS_STORE'; 
export const ADD_PROJECT_TASK = 'ADD_PROJECT_TASK'; 

export const ADD_TASK = 'ADD_TASK';
export const SET_TASKS = 'SET_TASKS';
export const CHANGE_TASK = 'CHANGE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const LOAD_TASK = 'LOAD_TASK';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';

export const ADD_LOCATION = 'ADD_LOCATION';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';

export const ADD_SKILL = 'ADD_SKILL';
export const SET_SKILLS = 'SET_SKILLS';
export const CHANGE_SKILL = 'CHANGE_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';

export const ADD_SKILL_LEVEL = 'ADD_SKILL_LEVEL';
export const SET_SKILL_LEVELS = 'SET_SKILL_LEVELS';
export const CHANGE_SKILL_LEVEL = 'CHANGE_SKILL_LEVEL';
export const REMOVE_SKILL_LEVEL = 'REMOVE_SKILL_LEVEL';

export const ADD_POSITION = 'ADD_POSITION';
export const SET_POSITIONS = 'SET_POSITIONS';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const REMOVE_POSITION = 'REMOVE_POSITION';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_HISTORY = 'SET_HISTORY';
export const LOAD = 'LOAD';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const SET_ISLOADING = 'SET_ISLOADING';
